networks:
  mgmt_net:
  instance_net:

services:
  backend:
    build: ./
    user: root
    restart: unless-stopped
    depends_on:
      valkey-mgmt:
        condition: service_healthy
    networks:
      - mgmt_net
      - instance_net
    environment:
      - VALDOCK_VALKEY_URL=valkey-mgmt:6379
      - VALDOCK_HOST=0.0.0.0
      - VALDOCK_PORT=8080
      - VALDOCK_INSTANCE_NET=valdock_instance_net
      - VALDOCK_INSTANCE_DATA_PATH=/mnt/c/Users/gpgvi/Desktop/testcontainers
      - ENV=production
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  valkey-mgmt:
    image: valkey/valkey:latest
    command: ["valkey-server", "--save", "60", "1", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 2s
      timeout: 1s
      retries: 10
    restart: unless-stopped
    volumes:
      - ./data/valkey-mgmt:/data
    networks:
      - mgmt_net
